export default {
  primaryKey: 'parameterId',
  autoQuery: false,
  selection: false,
  fields: [
    { name: 'parameterId', type: 'number' },
    { name: 'code', type: 'string' },
    { name: 'targetId', type: 'number' },
    { name: 'display', type: 'string' },
    { name: 'tableFieldName', type: 'string' },
    { name: 'title', type: 'string' },
    { name: 'description', type: 'string' },
    { name: 'lineNumber', type: 'number' },
    { name: 'columnNumber', type: 'number' },
    { name: 'displayLength', type: 'number' },
    { name: 'labelWidth', type: 'number' },
    { name: 'dataLength', type: 'number' },
    { name: 'required', type: 'string' },
    { name: 'readOnly', type: 'string' },
    { name: 'enabled', type: 'string' },
    { name: 'sourceType', type: 'string' },
    { name: 'sourceCode', type: 'string' },
    { name: 'sourceName', type: 'string' },
    { name: 'defaultType', type: 'string' },
    { name: 'defaultValue', type: 'string' },
    { name: 'defaultText', type: 'string' },
    { name: 'extraAttribute', type: 'string' },
  ],
};
